@0xceb823fa62cc7ffe;        # unique file ID generated by `capnp id`
using Java = import "java.capnp";

$Java.package("kafka.capnproto_serde.generated");
$Java.outerClassname("CapnProtoClasses");

struct PrimitiveMessage {
  timestamp @0 :Int64;
  query @1 :Text;
  pageNumber @2 :Int32;
  resultPerPage @3 :Int32;
}